// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj633XbaMuW0SR3wCC83ENOE6QqMWlJKg',
    appId: '1:809562731062:web:dedc17a9e3ee94fd6c1e97',
    messagingSenderId: '809562731062',
    projectId: 'easy-recipe-4ea07',
    authDomain: 'easy-recipe-4ea07.firebaseapp.com',
    storageBucket: 'easy-recipe-4ea07.firebasestorage.app',
    measurementId: 'G-VMKZVKPLKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnxsGXghGF_kqQy9S2jknHx1_iHjT9avk',
    appId: '1:809562731062:android:a124ff1e9b737dfc6c1e97',
    messagingSenderId: '809562731062',
    projectId: 'easy-recipe-4ea07',
    storageBucket: 'easy-recipe-4ea07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPj1EeBXyB1Q-b_nnH6nQR6suIQs78tCs',
    appId: '1:809562731062:ios:26ee3202eb186a406c1e97',
    messagingSenderId: '809562731062',
    projectId: 'easy-recipe-4ea07',
    storageBucket: 'easy-recipe-4ea07.firebasestorage.app',
    iosBundleId: 'com.example.easyRecipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPj1EeBXyB1Q-b_nnH6nQR6suIQs78tCs',
    appId: '1:809562731062:ios:26ee3202eb186a406c1e97',
    messagingSenderId: '809562731062',
    projectId: 'easy-recipe-4ea07',
    storageBucket: 'easy-recipe-4ea07.firebasestorage.app',
    iosBundleId: 'com.example.easyRecipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj633XbaMuW0SR3wCC83ENOE6QqMWlJKg',
    appId: '1:809562731062:web:02e8218acf7f89916c1e97',
    messagingSenderId: '809562731062',
    projectId: 'easy-recipe-4ea07',
    authDomain: 'easy-recipe-4ea07.firebaseapp.com',
    storageBucket: 'easy-recipe-4ea07.firebasestorage.app',
    measurementId: 'G-74DHHBP45X',
  );
}
